//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beauty
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking
    {
        public int id_booking { get; set; }
        public int id_client { get; set; }
        public int id_employee { get; set; }
        public System.DateTime Дата { get; set; }
        public System.TimeSpan Время { get; set; }
        public int id_service { get; set; }
    
        public virtual client client { get; set; }
        public virtual employee employee { get; set; }
        public virtual service service { get; set; }
    }
}
